:Author: tribhuvan
:Email: tribhuvanreddyramidi@gmail.com
:Date: 23/06/2017
:Revision: 1
:License: MIT

= Project: WEBserver using ESP8266.

This file creates a webserver with in ypur esp8266 using AT commands
AT+RST // reset module
AT+CWMODE=1 // configure as access point
AT+CIFSR // get ip address
AT+CIPMUX=1 // configure for multiple connections
AT+CIPSERVER=1,80 // turn on server on port 80
For more commands visit https://room-15.github.io/blog/2015/03/26/esp8266-at-command-reference/

== Step 1: Installation
1. Install Arduino plugin in operating system or simply login in to Arduino web editor(I would be using web editor)

2. Once logedin, once Arduino is connected to your computer web editor detects Arduino automatically


== Step 2: Assemble the circuit

Assemble the circuit following the diagram schematics.jpg attached to the sketch

== Step 3: Load the code

Upload sketchs to your account, then run it on 9600 baud rate

=== Folder structure

....
 connectTcp/                => Arduino sketch folder
  ├── getDataFromHtml.ino       => main Arduino file
  ├── schematics.jpg      => (optional) an image of the required schematics
  ├── sketch.json         => (optional) an image of the layout
  └── ReadMe.adoc         => this file
....

=== License
This project is released under a MIT License.

=== Contributing
To contribute to this project please contact tribhuvan <tribhuvanreddyramidi@gmail.com>

=== BOM

|===
| ID | Part name      | Part number | Quantity
| W1 | Male-Male wire | 1234-abcd   | 10       
| E1 | ESP8266        | 2345-asdf   | 1        
| A1 | Arduino Zero   | ABX00066    | 1     
| B1 | Bread board    | ABX00066    | 1        
|===


=== Help
This document is written in the _AsciiDoc_ format, a markup language to describe documents. 
If you need help you can search the http://www.methods.co.nz/asciidoc[AsciiDoc homepage]
or consult the http://powerman.name/doc/asciidoc[AsciiDoc cheatsheet]
